import webbrowser

print("Timetable Generator ")
print("Generate Timetable in Html Format Easily. ")
print("  ")
print("How to use ? ")
print("1) Just Fill the the All Necessary Fields asked here and press enter to continue. ")
print("2) If you want to leave any of Field empty just press Enter without entering any input. ")
print("3) After Entering all the fields your html file will be created and you will get redirected to the html page.")
print("4) Html File will be created on the same path where you kept this program.")

print("")
college = input("Enter your College / School name :")
classname = input("Enter your class :")
year = input("Enter your Academic Year:")
print("=========")
print(" Monday ")
print("=========")
m1 = input("Enter First Period :")
m2 = input("Enter Second Period :")
m3 = input("Enter Third Period :")
m4 = input("Enter Fourth Period :")
m5 = input("Enter Fifth Period :")
m6 = input("Enter Sixth Period :")
m7 = input("Enter Seventh Period :")
print("=========")
print(" Tuesday ")
print("=========")
t1 = input("Enter First Period :")
t2 = input("Enter Second Period :")
t3 = input("Enter Third Period :")
t4 = input("Enter Fourth Period :")
t5 = input("Enter Fifth Period :")
t6 = input("Enter Sixth Period :")
t7 = input("Enter Seventh Period :")
print("===========")
print(" Wednesday ")
print("===========")
w1 = input("Enter First Period :")
w2 = input("Enter Second Period :")
w3 = input("Enter Third Period :")
w4 = input("Enter Fourth Period :")
w5 = input("Enter Fifth Period :")
w6 = input("Enter Sixth Period :")
w7 = input("Enter Seventh Period :")
print("===========")
print(" Thursday ")
print("===========")
th1 = input("Enter First Period :")
th2 = input("Enter Second Period :")
th3 = input("Enter Third Period :")
th4 = input("Enter Fourth Period :")
th5 = input("Enter Fifth Period :")
th6 = input("Enter Sixth Period :")
th7 = input("Enter Seventh Period :")
print("===========")
print(" Friday ")
print("===========")
f1 = input("Enter First Period :")
f2 = input("Enter Second Period :")
f3 = input("Enter Third Period :")
f4 = input("Enter Fourth Period :")
f5 = input("Enter Fifth Period :")
f6 = input("Enter Sixth Period :")
f7 = input("Enter Seventh Period :")
print("===========")
print(" Saturday ")
print("===========")
s1 = input("Enter First Period :")
s2 = input("Enter Second Period :")
s3 = input("Enter Third Period :")
s4 = input("Enter Fourth Period :")
s5 = input("Enter Fifth Period :")
s6 = input("Enter Sixth Period :")
s7 = input("Enter Seventh Period :")

f = open('timetable.html','w')

code = "<!DOCTYPE html><html><head><title>Timetable</title> </head><body> <p><br>   </p> <font face='Arial'> <p><b>&nbsp " + college + " - " + classname + " ( " + year +" )</b></p> <table>  <tbody>  <tr>   <th>&nbspDay&nbsp</th> <th>&nbsp1&nbsp</th> <th>&nbsp2&nbsp</th> <th>&nbsp3&nbsp</th><th>&nbsp4&nbsp</th>          <th>&nbsp5&nbsp</th> <th>&nbsp6&nbsp</th> <th>&nbsp7&nbsp</th> </tr> <tr>   <td>&nbspMonday&nbsp</td>     <td>&nbsp" + m1 + "&nbsp</td> <td>&nbsp" + m2 + "&nbsp</td><td>&nbsp" + m3 + "&nbsp</td>   <td>&nbsp" + m4 + "&nbsp</td>   <td>&nbsp" + m5 + "&nbsp</td> <td>&nbsp" + m6 + "&nbsp</td>  <td>&nbsp" + m7 + "&nbsp</td>        </tr> <tr><td>&nbspTuesday&nbsp</td>  <td>&nbsp" + t1 + "&nbsp</td>  <td>&nbsp" + t2 + "&nbsp</td>     <td>&nbsp" + t3 + "&nbsp</td>    <td>&nbsp" + t4 + "&nbsp</td>  <td>&nbsp" + t5 + "&nbsp</td>   <td>&nbsp" + t6 + "&nbsp</td> <td>&nbsp" + t7 + "&nbsp</td>  </tr>   <tr>          <td>&nbspWednesday&nbsp</td><td>&nbsp" + w1 + "&nbsp</td> <td>&nbsp" + w2 + "&nbsp</td><td>&nbsp" + w3 + "&nbsp</td>  <td>&nbsp" + w4 + "&nbsp</td> <td>&nbsp" + w5 + "&nbsp</td><td>&nbsp" + w6 + "&nbsp</td>  <td>&nbsp" + w7 + "&nbsp</td>        </tr>  <tr>  <td>&nbspThursday&nbsp</td> <td>&nbsp" + th1 + "&nbsp</td> <td>&nbsp" + th2 + "&nbsp</td><td>&nbsp" + th3 + "&nbsp</td>   <td>&nbsp" + th4 + "&nbsp</td>         <td>&nbsp" + th5 + "&nbsp</td>         <td>&nbsp" + th6 + "&nbsp</td>         <td>&nbsp" + th7 + "&nbsp</td>        </tr>        <tr>          <td>&nbspFriday&nbsp</td>          <td>&nbsp" + f1 + "&nbsp</td>          <td>&nbsp" + f2 + "&nbsp</td>          <td>&nbsp" + f3 + "&nbsp</td>          <td>&nbsp" + f4 + "&nbsp</td>          <td>&nbsp" + f5 + "&nbsp</td>          <td>&nbsp" + f6 + "&nbsp</td>          <td>&nbsp" + f7 + "&nbsp</td>        </tr>        <tr>          <td>&nbspSaturday&nbsp</td>          <td>&nbsp" + s1 + "&nbsp</td>         <td>&nbsp" + s2 + "&nbsp</td>          <td>&nbsp" + s3 + "&nbsp</td>          <td>&nbsp" + s4 + "&nbsp</td>          <td>&nbsp" + s5 + "&nbsp</td>          <td>&nbsp" + s6 + "&nbsp</td>          <td>&nbsp" + s7 + "&nbsp</td>        </tr>      </tbody>    </table></font>  </body></html>"

f.write(code)
f.close()
webbrowser.open('timetable.html')
